services:
  - type: worker
    name: wppex-userbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python userbot/scheduler.py
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
